# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loopvision-gpu-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loopvision-gpu-api
  template:
    metadata:
      labels:
        app: loopvision-gpu-api
    spec:
      containers:
      - name: loopvision-inference-container
        image: asia-northeast3-docker.pkg.dev/ai-platform-453201/docker-ai-model-repo/loopvision-inference-api-gpu:v1
        ports:
        - containerPort: 5050
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: "1"
        env:
        - name: MODEL_PATH
          value: "./loopvision_2025Jun25.pth"
        - name: PYTORCH_ENABLE_MPS_FALLBACK
          value: "1"
      nodeSelector: # Use the correct label
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: loopvision-gpu-api-service
spec:
  selector:
    app: loopvision-gpu-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: LoadBalancer